### ISSUE TITLE
Crashing when setting properties in callbacks of certain signals

### ISSUE THREAD

**Issue by fcard** [JuliaLang/Gtk.jl#201] opened 2015-11-25 04:31 UTC
```julia
using Gtk.ShortNames

w = @Window
signal_connect(w, :delete_event) do widget, event
    visible(w, false)
    true
end

# *I close the window*
```
```
Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x63a5686a -- g_signal_handler_disconne
ct at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\b
in\libgobject-2.0-0.dll (unknown line)
g_signal_handler_disconnect at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64
-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit_valist at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw3
2\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys-r
oot\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv at C:\julia\packages\v0.4\WinRPM\deps\u
sr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_object_notify at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys
-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
gtk_toggle_button_accessible_get_type at C:\julia\packages\v0.4\WinRPM\deps\usr\
x86_64-w64-mingw32\sys-root\mingw\bin\libgtk-3-0.DLL (unknown line)
g_signal_handler_disconnect at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64
-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit_valist at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw3
2\sys-root\mingw\bin\libgobject-2.0-0.dll (unknown line)
g_signal_emit at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys-r
oot\mingw\bin\libgobject-2.0-0.dll (unknown line)
gtk_widget_hide at C:\julia\packages\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys
-root\mingw\bin\libgtk-3-0.DLL (unknown line)
visible at C:\julia\packages\v0.4\Gtk\src\base.jl:32
jlcall_visible_1662 at  (unknown line)
jl_apply_generic at C:\julia\Julia-0.4.x\bin\libjulia.dll (unknown line)
anonymous at none:2
jl_f_apply at C:\julia\Julia-0.4.x\bin\libjulia.dll (unknown line)
anonymous at C:\julia\packages\v0.4\Gtk\src\GLib\signals.jl:92
jl_switchto at C:\julia\Julia-0.4.x\bin\libjulia.dll (unknown line)

```

Something similar happens if I try changing the title of the window, or in the `:window_state_event` callback. It doesn't happen in the `:key_press_event`, or `:focus`.

This happened on Windows 8.1, using julia 0.4.1. It worked fine on Ubuntu (virtual machine).

This works:
```julia
c = Condition()
w = @Window
@spawn while true
    wait(c)
    sleep(0.1) # removing this causes crashing
    visible(w, false)
end
signal_connect(w, :delete_event) do widget, event
    notify(c)
    true
end
```

**Comment by vtjnash** [comment] 2015-11-25 04:35
duplicate of https://github.com/JuliaLang/Gtk.jl/issues/161

**Closed by vtjnash** 2015-11-25 04:35 UTC

**Comment by fcard** [comment] 2015-11-25 04:41
Ah okay, I suspect they were related but wasn't 100% sure. Thanks for your attention, and best of luck.
