### ISSUE TITLE
Julia crashes when using Gtk.jl

### ISSUE THREAD

**Issue by Staross** [JuliaLang/Gtk.jl#167] opened 2015-09-04 14:01 UTC
I'm trying to learn using Gtk.jl, but Julia (v. 0.3.11, windows 7) keep crashing when I'm running this code:

https://gist.github.com/Staross/8ac3f2aa6b99392c97fe

Am I doing something horribly wrong there or is that a bug? Julia crashes when I press return. Gtk tests passe. 

Here the error message:

`julia>
Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x63a55dda -- unknown function (ip: 167
1781850)
g_signal_handler_disconnect at  (unknown line)
gtk_entry_buffer_emit_deleted_text at  (unknown line)
setproperty! at C:\Users\Billou\.julia\v0.3\Gtk\src\GLib\gvalues.jl:163
jl_apply_generic at D:\Julia\Julia\bin\libjulia.dll (unknown line)
anonymous at D:\Julia\gtkCrash.jl:14
jl_f_apply at D:\Julia\Julia\bin\libjulia.dll (unknown line)
anonymous at C:\Users\Billou\.julia\v0.3\Gtk\src\GLib\signals.jl:92
jl_handle_stack_switch at D:\Julia\Julia\bin\libjulia.dll (unknown line)
julia_trampoline at D:\Julia\Julia\bin\libjulia.dll (unknown line)
unknown function (ip: 4202914)
unknown function (ip: 4199436)
unknown function (ip: 4199739)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)`

**Comment by timholy** [comment] 2015-09-04 15:21
Just a guess: see #161 and then read https://github.com/JuliaLang/Gtk.jl/blob/master/doc/more_signals.md (which fixed the problem for me).

**Comment by Staross** [comment] 2015-09-05 10:41
Thank you, this solved it. Maybe it should be mentioned in the main readme.

**Comment by timholy** [comment] 2015-09-05 20:05
Glad it worked.

If you have a good idea for how to phrase it, please just click on the README file, hit the pencil icon, and start editing.

**Comment by Staross** [comment] 2015-09-09 13:34
I'm not sure what's the status of the package with version 0.4, but I found almost any callback generate a segmentation fault when loading the file:

>using Gtk
win = @GtkWindow("A new window")

>function quit_cb(widgetptr::Ptr,eventptr::Ptr, user_data)
    println("exiting")
    return convert(Cint,false)
end
signal_connect(quit_cb, win, "delete-event", Cint, (Ptr{Gtk.GdkEvent},), false, ())

>julia> include("d:\\Julia\\gtkCrash.jl")

>Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7768afe2 -- RtlIsDosDeviceName_U at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlIsDosDeviceName_U at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
free at C:\Windows\system32\msvcrt.dll (unknown line)
utf8proc_NFKC at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_write_malloc_log at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_compile at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_compile at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_function_ptr at D:\Julia\Julia\bin\libjulia.dll (unknown line)
signal_connect at C:\Users\Billou\.julia\v0.4\Gtk\src\GLib\signals.jl:11
jlcall_signal_connect_1875 at  (unknown line)
jl_apply_generic at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_load_ at D:\Julia\Julia\bin\libjulia.dll (unknown line)
include at boot.jl:259
jl_apply_generic at D:\Julia\Julia\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:271
jl_apply_generic at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia\Julia\bin\libjulia.dll (unknown line)
jl_toplevel_eval_in at D:\Julia\Julia\bin\libjulia.dll (unknown line)
eval_user_input at REPL.jl:64
jlcall_eval_user_input_1278 at  (unknown line)
jl_apply_generic at D:\Julia\Julia\bin\libjulia.dll (unknown line)
anonymous at task.jl:93
jl_switchto at D:\Julia\Julia\bin\libjulia.dll (unknown line)

**Comment by vtjnash** [comment] 2015-09-09 13:40
calling `print` (or any form of `yield`) is something you are definitely not allowed to do during a callback (since this would hang the GUI stack).

**Comment by Staross** [comment] 2015-09-09 15:19
It doesn't depend on the content of the callback though. Note that it's crashing when the code in first loaded and signal_connect is called, not when the callback is executed (the application never quits).

**Comment by timholy** [comment] 2015-09-09 15:50
Leave off the final `()` in the argument list to `signal_connect`.

Also, the argument should be `Ptr{Gtk.GdkEventAny}`. Often it's a good idea to first try the simple version of a callback, written
```jl
signal_connect(win, "delete-event") do widget, event
    @show typeof(event)
    @show event
end
```

So that future users don't suffer the same way, it would be great if you'd add these tips to the docs.

**Comment by timholy** [comment] 2015-09-09 16:09
See #171.

**Comment by timholy** [comment] 2015-09-09 16:18
Probably only the second part, about trying the "simple version," is relevant; hopefully the underlying [julia bug](https://github.com/JuliaLang/julia/issues/13031) will be fixed soon.

**Comment by timholy** [comment] 2015-09-10 10:55
@Staross, I went ahead and added the documentation as part of #172.

**Comment by Staross** [comment] 2015-09-10 12:11
Thank you very much for the help, things are working fine now.

**Comment by vtjnash** [comment] 2015-12-27 18:01
duplicate of #161

**Closed by vtjnash** 2015-12-27 18:01 UTC
